spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root
    password: polo75312
  jpa:
    database: mysql
    generate-ddl: true
    hibernate.ddl.auto: update
    show-sql: true
aws:
  s3:
    access-id: YOUR ID
    access-pw: YOUR PASSWORD
    bucket: s3 이름
